sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
script:
  - make
addons:
    apt:
        packages: gfortran
    homebrew:
        packages: gfortran
