sudo: required
matrix:
  include:
    - name: Quick Linux build
      os: linux
      dist: xenial
      language: python
      python: "3.7"
      env: PYPI_DEPLOY=0  # Linux binary wheel must be created using a manylinux docker image, see below
    - name: macOS 10.15.14 with Xcode 11.5
      os: osx
      osx_image: xcode11.5
      language: generic
      # Use praekeltfoundation/travis-pyenv to workaround Travis not supporting
      # Python builds on MacOS out of the box. (The issue was that Python 2.7
      # was being picked up during the deploy step).
      env:
          PYENV_VERSION='3.7.7'
          PYENV_VERSION_STRING='Python 3.7.7'
          PYPI_DEPLOY=1
      before_install:
        - wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        - source setup-pyenv.sh
    - name: manylinux2014
      dist: bionic
      language: python
      python: "3.7"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PYPI_DEPLOY=1
      install:
        - docker pull $DOCKER_IMAGE
      before_script:
        - >
            docker run --rm -v `pwd`:/io $DOCKER_IMAGE /bin/bash -xc '
            PYBIN="/opt/python/cp37-cp37m/bin/" &&
            "$PYBIN"/pip install pep517 &&
            "$PYBIN"/python -m pep517.build --source --binary /io/ &&
            ORIGINAL_WHEEL="$(ls /io/dist/*.whl)" &&
            auditwheel show "$ORIGINAL_WHEEL" &&
            auditwheel repair "$ORIGINAL_WHEEL" --plat manylinux2014_x86_64 -w /io/dist/ &&
            rm "$ORIGINAL_WHEEL"
            '
cache:
  - directories:
    - $HOME/.pyenv_cache
script:
  - find / -name libgfortran.a 2>/dev/null
  - find / -name libquadmath.a 2>/dev/null
  # Build only if artifacts not already present (as will be the case with the
  # manylinux build, which requires post-processing in container).
  - if [[ ! -d dist ]] ; then pip install pep517 && python -m pep517.build --source --binary . ; fi
  - ldd resp || otool -L resp
  - pip install -v restrained-ESP-fit --no-index --only-binary restrained-ESP-fit -f dist/
  - restrained_ESP_fit  # The target `resp` binary always returns 0
  - pip install twine
  - twine check dist/*
  # TODO: Try to only deploy tagged commits (and when PYPI_DEPLOY variable is set)
  # - twine upload --skip-existing --repository-url https://test.pypi.org/legacy -u "__token__" -p "$TEST_PYPI_TOKEN" dist/*
addons:
    apt:
        packages: gfortran
    homebrew:
        packages: gfortran
