sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11.5
language: python
python: "3.8"
script:
  - pip install -e .
  - restrained_ESP_fit
addons:
    apt:
        packages: gfortran
    homebrew:
        packages: gfortran
