matrix:
  include:
    - name: Quick Linux build
      os: linux
      dist: xenial  # Ubuntu 16.04, reasonably old and LTS
      language: python
      python: "3.7"
      env:
        # Linux binary wheel must be created using a manylinux docker image,
        # see build job below.
        - PYPI_DEPLOY=0
        - PYPI_PLAT=linux_x86_64
        - VPATH_DIR=/usr/lib/gcc/x86_64-linux-gnu/5
    - name: macOS 10.15.4 with Xcode 11.6
      os: osx
      osx_image: xcode11.6
      language: generic
      env:
        - PYENV_VERSION='3.7.7'
        - PYENV_VERSION_STRING='Python 3.7.7'
        - PYPI_DEPLOY=1
        - PYPI_PLAT=macosx_10_15_x86_64
        # Using an older gcc because newer ones actually use clang and I
        # wasn't able to statically link libquadmath with it.
        - GCC_OVERRIDE=/usr/local/bin/gcc-4.9
        - VPATH_DIR=/usr/local/Cellar/gcc@4.9/4.9.4_2/lib/gcc/4.9
      before_install:
        # Use praekeltfoundation/travis-pyenv to workaround Travis not
        # supporting Python builds on macOS out of the box. (The issue was that
        # Python 2.7 was being picked up during the deploy step).
        - wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        - source setup-pyenv.sh
    - name: manylinux2014
      dist: bionic
      language: python
      python: "3.7"
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
        - PYPI_DEPLOY=1
        - PYPI_PLAT=manylinux2014_x86_64
        - VPATH_DIR=/opt/rh/devtoolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9
      install:
        - docker pull $DOCKER_IMAGE
      before_script:
        - >
          docker run \
            --rm \
            -e VPATH_DIR="$VPATH_DIR" \
            -e PYPI_PLAT="$PYPI_PLAT" \
            -v `pwd`:/io \
            -w /io \
            $DOCKER_IMAGE \
            /bin/bash -xc '
              PYBIN="/opt/python/cp37-cp37m/bin/" &&
              "$PYBIN"/python setup.py sdist bdist_wheel --python-tag py3 --plat="$PYPI_PLAT"
              # ORIGINAL_WHEEL="$(ls /io/dist/*.whl)" &&
              # auditwheel show "$ORIGINAL_WHEEL" &&
              # auditwheel repair "$ORIGINAL_WHEEL" --plat manylinux2014_x86_64 -w /io/dist/ &&
              # rm "$ORIGINAL_WHEEL"
            '
cache:
  - directories:
    - $HOME/.pyenv_cache
script:
  # Build only if artifacts not already present (as will be the case with the
  # manylinux build, which requires post-processing in container).
  - if [[ ! -d dist ]] ; then python setup.py sdist bdist_wheel --python-tag py3 --plat="$PYPI_PLAT" ; fi
  - ldd resp || otool -L resp
  - pip install -v restrained-ESP-fit --no-index --only-binary restrained-ESP-fit -f dist/
  - restrained_ESP_fit  # The target `resp` binary always returns 0
  # TODO: Add some tests
  - pip install twine
  - twine check dist/*
after_success:
  - >
    if [[ $(git tag --points-at HEAD | head -c1 | wc -c) -ne 0 && "$PYPI_DEPLOY" -eq 1 ]] ; then
      echo "Build successful, tagged commit and job marked for deployment --- deploying..."
      twine upload --skip-existing --repository-url https://test.pypi.org/legacy -u "__token__" -p "$TEST_PYPI_TOKEN" dist/*
    else \
      echo "Build successful but criteria not met, not deploying."
    fi
addons:
  apt:
    packages: gfortran
  homebrew:
    packages: gcc@4.9
