sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.7"
      env: PYPI_DEPLOY=0  # Linux binary wheel must be created using a manylinux docker image, see below
    - os: osx
      osx_image: xcode11.5
      language: generic
      # Use praekeltfoundation/travis-pyenv to workaround Travis not supporting
      # Python builds on MacOS out of the box. (The issue was that Python 2.7
      # was being picked up during the deploy step).
      env: PYENV_VERSION='3.7.7' PYENV_VERSION_STRING='Python 3.7.7' PYPI_DEPLOY=1
      before_install:
        - wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        - source setup-pyenv.sh
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PYPI_DEPLOY=1
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - >
            docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /bin/bash -c '
            PYBIN="/opt/python/cp37-cp37m/bin/" &&
            "$PYBIN"/pip --version &&
            "$PYBIN"/pip wheel /io/ --no-deps -w wheelhouse/ &&
            WHEEL="/io/wheelhouse/$(ls wheelhouse/*.whl)" &&
            auditwheel show "$WHEEL" &&
            auditwheel repair "$WHEEL" --plat manylinux2014_x86_64 -w /io/wheelhouse/ &&
            "$PYBIN"/pip install restrained-ESP-fit --no-index -f /io/wheelhouse
            # TODO: Move this to the common script section, along with a test
            # invocation and publishing (including an sdist).
            '
        - ls wheelhouse/
cache:
  - directories:
    - $HOME/.pyenv_cache
script:
  - pip3 install -ve .
  - restrained_ESP_fit  # The target `resp` binary always returns 0
addons:
    apt:
        packages: gfortran
    homebrew:
        packages: gfortran
deploy:
    provider: pypi
    server: https://test.pypi.org/legacy/
    username: "__token__"
    password: $TEST_PYPI_TOKEN
    distributions: "sdist bdist_wheel"
    skip_existing: true
    edge: true # opt in to dpl v2
    on:
        branch: travis-publish-pypi
        condition: $PYPI_DEPLOY = 1
