sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.7"
      env: PYPI_DEPLOY=0  # Linux binary wheel must be created using a manylinux docker image, see below
    - os: osx
      osx_image: xcode11.5
      language: generic
      # Use praekeltfoundation/travis-pyenv to workaround Travis not supporting
      # Python builds on MacOS out of the box. (The issue was that Python 2.7
      # was being picked up during the deploy step).
      env: PYENV_VERSION='3.7.7' PYENV_VERSION_STRING='Python 3.7.7' PYPI_DEPLOY=1
      before_install:
        - wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        - source setup-pyenv.sh
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PYPI_DEPLOY=1
      install:
        - docker pull $DOCKER_IMAGE
      before_script:
        - >
            docker run --rm -v `pwd`:/io $DOCKER_IMAGE /bin/bash -xc '
            PYBIN="/opt/python/cp37-cp37m/bin/" &&
            "$PYBIN"/pip install pep517 &&
            "$PYBIN"/python -m pep517.build --source --binary /io/ &&
            ORIGINAL_WHEEL="$(ls /io/dist/*.whl)" &&
            auditwheel show "$ORIGINAL_WHEEL" &&
            auditwheel repair "$ORIGINAL_WHEEL" --plat manylinux2014_x86_64 -w /io/dist/ &&
            rm "$ORIGINAL_WHEEL"
            '
        - ls dist/
cache:
  - directories:
    - $HOME/.pyenv_cache
script:
  - which pip
  - which pip3
  - which python
  - which python3
  - if [[ ! -d dist ]] ; then pip install pep517 && python -m pep517.build --source --binary . ; fi
    # Fail if any command here fails (not the default I think)
  # - pip install restrained-ESP-fit --no-index -f dist/
  # - restrained_ESP_fit  # The target `resp` binary always returns 0
  # - twine check dist/*
  #   # How to only deploy on tagged + PYPI_DEPLOY variable set?
  # - twine upload --skip-existing --repository-url https://test.pypi.org/legacy -u "__token__" -p "$TEST_PYPI_TOKEN" dist/*
addons:
    apt:
        packages: gfortran
    homebrew:
        packages: gfortran
