sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
language: c
before_install:
  - sudo apt-get install gfortran
script:
  - make
  - ./restricted_ESP_fit
