sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.7"
    - os: osx
      osx_image: xcode11.5
      language: generic
      # Use praekeltfoundation/travis-pyenv to workaround Travis not supporting
      # Python builds on MacOS out of the box. (The issue was that Python 2.7
      # was being picked up during the deploy step).
      env: PYENV_VERSION='3.7.7' PYENV_VERSION_STRING='Python 3.7.7'
      before_install:
        - wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        - source setup-pyenv.sh
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PLAT=manylinux2014_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - wget https://raw.githubusercontent.com/pypa/python-manylinux-demo/84dc72039a0c85c1c960e024f024fd3d37387634/travis/build-wheels.sh
        - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD build-wheels.sh
        - ls wheelhouse/
cache:
  - directories:
    - $HOME/.pyenv_cache
script:
  - pip3 install -ve .
  - restrained_ESP_fit  # The target `resp` binary always returns 0
addons:
    apt:
        packages: gfortran
    homebrew:
        packages: gfortran
deploy:
    provider: pypi
    server: https://test.pypi.org/legacy/
    username: "__token__"
    password: $TEST_PYPI_TOKEN
    distributions: "sdist bdist_wheel"
    skip_existing: true
    edge: true # opt in to dpl v2
    on:
        tags: true
        condition: os != linux
