name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  # TODO: Add a scheduled job for master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            WHEEL_PLAT: linux_x86_64
            RESTRAINED_ESP_FIT_RESP_VPATH_DIR: /usr/lib/gcc/x86_64-linux-gnu/7

          - os: macos-10.15
            WHEEL_PLAT: macosx_10_15_x86_64
            RESTRAINED_ESP_FIT_RESP_STATIC: 1
            # Using an older gcc because newer ones actually use clang and I
            # wasn't able to statically link libquadmath with it.
            RESTRAINED_ESP_FIT_RESP_GCC_OVERRIDE: /usr/local/bin/gcc-4.9
            RESTRAINED_ESP_FIT_RESP_VPATH_DIR: /usr/local/Cellar/gcc@4.9/4.9.4_2/lib/gcc/4.9

    env:
      WHEEL_PLAT: ${{ matrix.WHEEL_PLAT}}
      RESTRAINED_ESP_FIT_RESP_GCC_OVERRIDE: ${{ matrix.RESTRAINED_ESP_FIT_RESP_GCC_OVERRIDE}}
      RESTRAINED_ESP_FIT_RESP_VPATH_DIR: ${{ matrix.RESTRAINED_ESP_FIT_RESP_VPATH_DIR}}

    steps:
    - uses: actions/checkout@v2

    - name: Test environment variables dependent on the OS
      run: echo "$RESTRAINED_ESP_FIT_RESP_VPATH_DIR"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build sdist and bdist_wheel
      run: python setup.py sdist bdist_wheel --python-tag py3 --plat="$WHEEL_PLAT"

    - name: Verify that libraries are linked as expected
      run: ldd ./restrained_ESP_fit/build/resp || otool -L ./restrained_ESP_fit/build/resp

    - name: Test installing from source, which should still work if gfortran is available
      run: pip install -v restrained-ESP-fit --no-index --no-binary restrained-ESP-fit -f dist/

    - name: Run the `resp` binary in lieu of tests (returns 0)
      run: restrained_ESP_fit

    - name: Uninstall restrained-ESP-fit...
      run: pip uninstall --yes restrained-ESP-fit

    - name: ...in order to test installing from the binary wheel
      run: pip install -v restrained-ESP-fit --no-index --only-binary restrained-ESP-fit -f dist/

    - name: Run the `resp` binary in lieu of tests (returns 0)
      run: restrained_ESP_fit

    - name: Check if package passes validation for publishing to PyPI
      run: twine check dist/*
